### Como usar:
#
# docker login https://dti-registro.unilab.edu.br
# docker build -t dti-registro.unilab.edu.br/unilab/app-3s:main .
# docker push dti-registro.unilab.edu.br/unilab/app-3s:main
# docker-compose up -d
# docker-compose logs -f
# docker exec -it 3s-debug /bin/bash
# docker-compose down

version: '3.9'
services:
  ###################################
  # Application
  ###################################
  app-dev-debug:
    build:
      context: .
      dockerfile: Dockerfile
    image: dti-registro.unilab.edu.br/unilab/app-3s:main
    container_name: 3s-debug
    restart: always
    user: "root:www-data"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - "8083:80"
      - "22:22"
    networks:
      - developer

  ###################################
  # PostgreSQL (Optional BD Local)
  ###################################
  postgresql:
    image: postgres:15-bullseye
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ocorrencias
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - developer

volumes:
  postgresql_data:
    driver: local

networks:
 developer:
   name: developer
   driver: bridge